In [1]:
import time
import os
import pandas as pd
from datetime import datetime, timedelta
from tqdm.notebook import tqdm_notebook
tqdm_notebook.pandas()

In [2]:
data = {'time': [], 'predicted': []}
start_time = datetime(2020,7,1,0,0,0)
end_time = datetime(2021,7,2,0,0,0)

In [3]:
while start_time < end_time:
    pred_time = start_time
    for i in range(12):
        pred_time += timedelta(hours=6)
        data['time'].append(start_time)
        data['predicted'].append(pred_time)
    start_time += timedelta(hours=6)

In [4]:
df = pd.DataFrame.from_dict(data)

In [6]:
df.head(20)

                  time           predicted
0  2020-07-01 00:00:00 2020-07-01 06:00:00
1  2020-07-01 00:00:00 2020-07-01 12:00:00
2  2020-07-01 00:00:00 2020-07-01 18:00:00
3  2020-07-01 00:00:00 2020-07-02 00:00:00
4  2020-07-01 00:00:00 2020-07-02 06:00:00
5  2020-07-01 00:00:00 2020-07-02 12:00:00
6  2020-07-01 00:00:00 2020-07-02 18:00:00
7  2020-07-01 00:00:00 2020-07-03 00:00:00
8  2020-07-01 00:00:00 2020-07-03 06:00:00
9  2020-07-01 00:00:00 2020-07-03 12:00:00
10 2020-07-01 00:00:00 2020-07-03 18:00:00
11 2020-07-01 00:00:00 2020-07-04 00:00:00
12 2020-07-01 06:00:00 2020-07-01 12:00:00
13 2020-07-01 06:00:00 2020-07-01 18:00:00
14 2020-07-01 06:00:00 2020-07-02 00:00:00
15 2020-07-01 06:00:00 2020-07-02 06:00:00
16 2020-07-01 06:00:00 2020-07-02 12:00:00
17 2020-07-01 06:00:00 2020-07-02 18:00:00
18 2020-07-01 06:00:00 2020-07-03 00:00:00
19 2020-07-01 06:00:00 2020-07-03 06:00:00

In [8]:
df.to_csv('submit_time_format.csv',index=False)