In [1]:
import pandas as pd

In [3]:
provinces = ['BKK','Chiangmai','Khonkaen','Rayong','Saraburi','Surat']
province = provinces[0]

data_test = pd.read_csv(province+'_clean.csv', date_parser = True)
data_test = data_test.drop(['Unnamed: 0', 'lat', 'long'], axis = 1)
data_test.head()

             date_time  PM2.5  temp  wind speed  wind dir
0  2020-07-01 00:00:00    9.0  29.4          35       270
1  2020-07-01 01:00:00    8.0  29.4          42       260
2  2020-07-01 02:00:00   12.0  28.5          42       260
3  2020-07-01 03:00:00    9.0  28.5          42       260
4  2020-07-01 04:00:00    8.0  28.3          55       270

In [11]:
def chk_time(x):
    
    if(x[11:13] in ['00','06','12','18']):
        return True
    return False

In [13]:
data_test['chk_time'] = data_test['date_time'].apply(lambda x: chk_time(x))
data_test.head(10)

             date_time  PM2.5  temp  wind speed  wind dir  chk_time
0  2020-07-01 00:00:00    9.0  29.4          35       270      True
1  2020-07-01 01:00:00    8.0  29.4          42       260     False
2  2020-07-01 02:00:00   12.0  28.5          42       260     False
3  2020-07-01 03:00:00    9.0  28.5          42       260     False
4  2020-07-01 04:00:00    8.0  28.3          55       270     False
5  2020-07-01 05:00:00   11.0  28.3          55       270     False
6  2020-07-01 06:00:00   11.0  28.3          55       270      True
7  2020-07-01 07:00:00   13.0  28.7          53       250     False
8  2020-07-01 08:00:00   12.0  28.7          53       250     False
9  2020-07-01 09:00:00   12.0  28.7          53       250     False

In [14]:
data_test = data_test[data_test['chk_time']]
data_test.head(10)

              date_time  PM2.5  temp  wind speed  wind dir  chk_time
0   2020-07-01 00:00:00    9.0  29.4          35       270      True
6   2020-07-01 06:00:00   11.0  28.3          55       270      True
12  2020-07-01 12:00:00   15.0  29.7          51       260      True
18  2020-07-01 18:00:00   14.0  29.5          35       265      True
24  2020-07-02 00:00:00   18.0  28.7          60       275      True
30  2020-07-02 06:00:00   12.0  28.4          40       275      True
36  2020-07-02 12:00:00   10.0  30.8          34       270      True
42  2020-07-02 18:00:00   10.0  31.6          27       255      True
48  2020-07-03 00:00:00   13.0  29.1          34       275      True
54  2020-07-03 06:00:00   20.0  28.3          40       285      True

In [17]:
data_test.drop(['chk_time'],axis=1,inplace=True)

In [18]:
data_test

                date_time  PM2.5  temp  wind speed  wind dir
0     2020-07-01 00:00:00    9.0  29.4          35       270
6     2020-07-01 06:00:00   11.0  28.3          55       270
12    2020-07-01 12:00:00   15.0  29.7          51       260
18    2020-07-01 18:00:00   14.0  29.5          35       265
24    2020-07-02 00:00:00   18.0  28.7          60       275
...                   ...    ...   ...         ...       ...
8754  2021-06-30 18:00:00   15.0  26.0          29       270
8760  2021-07-01 00:00:00   15.0  28.4          20       265
8766  2021-07-01 06:00:00   14.0  26.5          21       275
8772  2021-07-01 12:00:00   14.0  32.3          17       245
8778  2021-07-01 18:00:00   14.0  31.2          21       245

[1464 rows x 5 columns]

In [20]:
data_test.to_csv(province+'_clean2.csv',index=False)